### ISSUE TITLE
Contact is "never shown" at least it says that

### ISSUE THREAD

**Issue by Pukimaa** [okikio/okikio#12]
I am on the latest Pop OS! which is based on Ubuntu 21.10 with Chrome 100 installed.

When I visit your site on a big enough monitor and I click on contact it brings me to there but it still shows I would be in projects. This is probably due to you checking if screen is fully filled with this section. You probably need to change the logic you are currently using. Or at least if the url is `/#contact` that the contact nav item is active.

![screenshot](https://user-images.githubusercontent.com/58347116/163371429-8f8077c6-c886-4b40-b196-9f4ac603344c.png)

**Comment by okikio** [comment]
This should be fixed please tell me what you think?

**Comment by Pukimaa** [comment]
Works like intended now. Great work btw!

**Comment by okikio** [comment]
Thanks.
